# Generated by Django 5.0.1 on 2024-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationofficedepartment',
            name='phone_no',
            field=models.CharField(default='None', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='buildingestatedepartment',
            name='phone_no',
            field=models.CharField(default='None', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(default='None', max_length=15, null=True),
        ),
    ]
